/* tslint:disable */
require("./CopilotDiagnostics.module.css");
const styles = {
  container: 'container_edc9b1ea',
  header: 'header_edc9b1ea',
  headerIcon: 'headerIcon_edc9b1ea',
  title: 'title_edc9b1ea',
  subtitle: 'subtitle_edc9b1ea',
  configRow: 'configRow_edc9b1ea',
  configField: 'configField_edc9b1ea',
  label: 'label_edc9b1ea',
  modeToggle: 'modeToggle_edc9b1ea',
  modeBtn: 'modeBtn_edc9b1ea',
  modeBtnActive: 'modeBtnActive_edc9b1ea',
  select: 'select_edc9b1ea',
  inputRow: 'inputRow_edc9b1ea',
  questionInput: 'questionInput_edc9b1ea',
  runBtn: 'runBtn_edc9b1ea',
  btnSpinner: 'btnSpinner_edc9b1ea',
  tipsBox: 'tipsBox_edc9b1ea',
  tipsIcon: 'tipsIcon_edc9b1ea',
  results: 'results_edc9b1ea',
  resultsTitle: 'resultsTitle_edc9b1ea',
  runCard: 'runCard_edc9b1ea',
  runCardError: 'runCardError_edc9b1ea',
  runHeader: 'runHeader_edc9b1ea',
  runBadge: 'runBadge_edc9b1ea',
  runBadgeSync: 'runBadgeSync_edc9b1ea',
  runBadgeStream: 'runBadgeStream_edc9b1ea',
  runQuestion: 'runQuestion_edc9b1ea',
  runTime: 'runTime_edc9b1ea',
  runTotal: 'runTotal_edc9b1ea',
  runTotalFast: 'runTotalFast_edc9b1ea',
  runSpinner: 'runSpinner_edc9b1ea',
  chevron: 'chevron_edc9b1ea',
  runDetail: 'runDetail_edc9b1ea',
  errorBox: 'errorBox_edc9b1ea',
  timingTable: 'timingTable_edc9b1ea',
  timingValue: 'timingValue_edc9b1ea',
  timingValueHighlight: 'timingValueHighlight_edc9b1ea',
  timingKey: 'timingKey_edc9b1ea',
  timingNote: 'timingNote_edc9b1ea',
  timingRowTotal: 'timingRowTotal_edc9b1ea',
  chunkSection: 'chunkSection_edc9b1ea',
  chunkHeader: 'chunkHeader_edc9b1ea',
  chunkCount: 'chunkCount_edc9b1ea',
  chunkWaiting: 'chunkWaiting_edc9b1ea',
  diagnosis: 'diagnosis_edc9b1ea',
  diagnosisGood: 'diagnosisGood_edc9b1ea',
  diagnosisBad: 'diagnosisBad_edc9b1ea',
  chunkTimeline: 'chunkTimeline_edc9b1ea',
  chunkPill: 'chunkPill_edc9b1ea',
  chunkPillMore: 'chunkPillMore_edc9b1ea',
  responseSection: 'responseSection_edc9b1ea',
  responseSectionTitle: 'responseSectionTitle_edc9b1ea',
  responseText: 'responseText_edc9b1ea'
};

export default styles;
/* tslint:enable */